---
- name: Install Harbor on Ubuntu 22.04
  hosts: harbor
  become: true
  vars:
    harbor_version: "2.13.0"
    harbor_install_dir: "/opt/harbor"
    harbor_config_file: "/opt/harbor/harbor.yml"
    harbor_download_url: "https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}/harbor-online-installer-v{{ harbor_version }}.tgz"
  roles:
    - roles/docker
  tasks:
    - name: Ensure Harbor installation directory exists
      ansible.builtin.file:
        path: "{{ harbor_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Download Harbor installer
      ansible.builtin.get_url:
        url: "{{ harbor_download_url }}"
        dest: "/tmp/harbor-online-installer-v{{ harbor_version }}.tgz"

    - name: Extract Harbor installer
      ansible.builtin.unarchive:
        src: "/tmp/harbor-online-installer-v{{ harbor_version }}.tgz"
        dest: "{{ harbor_install_dir }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1

    - name: Copy Harbor configuration file
      ansible.builtin.template:
        src: "../templates/harbor.yml.j2"
        dest: "{{ harbor_config_file }}"
        owner: root
        group: root
        mode: 0644
      vars:
        harbor_hostname: "{{ hostvars[groups['harbor'][0]]['ansible_host'] }}"

    - name: Install Harbor
      ansible.builtin.command:
        cmd: "./install.sh"
        chdir: "{{ harbor_install_dir }}"
    #   environment:
    #     DOCKER_COMPOSE: "/usr/libexec/docker/cli-plugins/docker-compose"

    # - name: Start Harbor services
    #   ansible.builtin.command:
    #     cmd: "docker compose up -d"
    #     chdir: "{{ harbor_install_dir }}"