- name: Prepare
  hosts: k8s_master,k8s_worker
  become: true
  tasks:
  # Disabling Swap 
  - name: Disable Swap
    mount:
      name: none
      fstype: swap
      state: absent

  - name: Unmount Swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add Kubernetes node entries to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      state: present
    loop:
      - "10.0.129.10 k8s-master-vm-01"
      - "10.0.129.11 k8s-worker-vm-01"
      - "10.0.129.12 k8s-worker-vm-02"

  - name: Enable Require Modules
    modprobe:
      state: present
      name: "{{ item }}"
    loop: [overlay,br_netfilter]

  - name: Configure sysctl for Kubernetes
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      sysctl_set: yes
      reload: yes
    loop:
      - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
      - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
      - { name: 'net.ipv4.ip_forward', value: '1' }

- name: Install Docker and configure containerd
  hosts: k8s_master,k8s_worker
  become: true
  tasks:
    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install required packages
    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    # Create directory for Docker GPG key
    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Download Docker's GPG key
    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    # Add Docker repository
    - name: Add Docker repository
      copy:
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'

    # Update apt cache after adding Docker repository
    - name: Update apt cache after adding Docker repository
      apt:
        update_cache: yes

    # Install Docker packages
    - name: Install Docker packages
      apt:
        name: containerd.io
        state: present

    # Generate default containerd configuration
    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config
      changed_when: false

    # Write containerd configuration to file
    - name: Write containerd configuration to file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    # Update containerd configuration to use systemd cgroup
    - name: Ensure SystemdCgroup is set to true
      replace:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup\s*=.*'
        replace: '            SystemdCgroup = true'

    # Restart and enable containerd
    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

- name: Install kubeadm, kubelet, and kubectl
  hosts: k8s_master,k8s_worker
  become: true
  tasks:
    # Ensure no other process is holding the dpkg lock
    - name: Ensure no other process is holding the dpkg lock
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
          echo "Waiting for other apt processes to finish..."
          sleep 5
        done
      changed_when: false

    # Update apt package index
    - name: Update apt package index
      apt:
        update_cache: yes

    # Install required packages
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    # Create directory for Kubernetes GPG key
    - name: Create directory for Kubernetes GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

      # Download Kubernetes GPG key
    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'

    - name: Dearmor Kubernetes GPG key
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key

    - name: Remove temporary GPG key file
      file:
        path: /tmp/kubernetes-release.key
        state: absent

    # Add Kubernetes apt repository
    - name: Add Kubernetes apt repository
      copy:
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'

    # Update apt package index after adding Kubernetes repository
    - name: Update apt package index after adding Kubernetes repository
      apt:
        update_cache: yes

    # Install kubeadm, kubelet, and kubectl
    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    # Mark kubeadm, kubelet, and kubectl to hold their versions
    - name: Hold kubeadm, kubelet, and kubectl versions
      command: apt-mark hold kubelet kubeadm kubectl

    # Enable and start kubelet service
    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: yes
