---
- name: Initialize Kubernetes Master
  hosts: k8s_master
  become: true
  tasks:
    - name: Extract join command
      shell: |
        kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Print join command
      debug:
        msg: "{{ join_command.stdout }}"

- name: Join Kubernetes Worker Nodes
  hosts: k8s_worker
  become: true
  tasks:
    - name: Check if worker node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join worker nodes to the cluster
      command: "{{ hostvars[groups['k8s_master'][0]].join_command.stdout }}"
      when: not kubelet_conf.stat.exists

    - name: Print join command for worker nodes
      debug:
        msg: "{{ hostvars[groups['k8s_master'][0]].join_command.stdout }}"
      when: not kubelet_conf.stat.exists