---
- name: Install Helm on Kubernetes Master
  hosts: k8s_master
  become: true
  tasks:
    # Download Helm binary
    - name: Download Helm binary
      get_url:
        url: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz
        mode: '0644'

    # Extract Helm binary
    - name: Extract Helm binary
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp/
        remote_src: yes

    # Move Helm binary to /usr/local/bin
    - name: Move Helm binary to /usr/local/bin
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm

    # Ensure Helm binary is executable
    - name: Ensure Helm binary is executable
      file:
        path: /usr/local/bin/helm
        mode: '0755'
        state: file

    # Verify Helm installation
    - name: Verify Helm installation
      command: helm version
      register: helm_version_output

    - name: Print Helm version
      debug:
        msg: "{{ helm_version_output.stdout }}"