- name: Create an NGINX pod and service for testing
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create an NGINX pod
      kubernetes.core.k8s:
        state: present
        src: ../files/test_k8s.yaml
        kubeconfig: /home/ubuntu/.kube/config