---
- name: Add insecure registry to containerd config
  hosts: k8s_worker
  become: true
  tasks:
    # Generate default containerd configuration
    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config
      changed_when: false

    # Write containerd configuration to file
    - name: Write containerd configuration to file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config2.toml

    # Write containerd configuration to file
    - name: Replace registry mirrors block in containerd config
      blockinfile:
        path: /etc/containerd/config2.toml
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR REGISTRY MIRRORS"
        block: |
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."172.16.204.150"]
              endpoint = ["http://172.16.204.150"]

    # - name: Restart containerd service
    #   service:
    #     name: containerd
    #     state: restarted